export const majorCities = [
  { label: "New York", value: "New York", state: "NY" },
  { label: "Los Angeles", value: "Los Angeles", state: "CA" },
  { label: "Chicago", value: "Chicago", state: "IL" },
  { label: "Houston", value: "Houston", state: "TX" },
  { label: "Phoenix", value: "Phoenix", state: "AZ" },
  { label: "Philadelphia", value: "Philadelphia", state: "PA" },
  { label: "San Antonio", value: "San Antonio", state: "TX" },
  { label: "San Diego", value: "San Diego", state: "CA" },
  { label: "Dallas", value: "Dallas", state: "TX" },
  { label: "San Jose", value: "San Jose", state: "CA" },
  { label: "Austin", value: "Austin", state: "TX" },
  { label: "Jacksonville", value: "Jacksonville", state: "FL" },
  { label: "San Francisco", value: "San Francisco", state: "CA" },
  { label: "Indianapolis", value: "Indianapolis", state: "IN" },
  { label: "Columbus", value: "Columbus", state: "OH" },
  { label: "Fort Worth", value: "Fort Worth", state: "TX" },
  { label: "Charlotte", value: "Charlotte", state: "NC" },
  { label: "Detroit", value: "Detroit", state: "MI" },
  { label: "El Paso", value: "El Paso", state: "TX" },
  { label: "Memphis", value: "Memphis", state: "TN" },
  { label: "Baltimore", value: "Baltimore", state: "MD" },
  { label: "Boston", value: "Boston", state: "MA" },
  { label: "Washington", value: "Washington", state: "DC" },
  { label: "Nashville", value: "Nashville", state: "TN" },
  { label: "Denver", value: "Denver", state: "CO" },
  { label: "Seattle", value: "Seattle", state: "WA" },
  { label: "Omaha", value: "Omaha", state: "NE" },
  { label: "Las Vegas", value: "Las Vegas", state: "NV" },
  { label: "Louisville", value: "Louisville", state: "KY" },
  { label: "Milwaukee", value: "Milwaukee", state: "WI" },
  { label: "Albuquerque", value: "Albuquerque", state: "NM" },
  { label: "Tucson", value: "Tucson", state: "AZ" },
  { label: "Fresno", value: "Fresno", state: "CA" },
  { label: "Sacramento", value: "Sacramento", state: "CA" },
  { label: "Kansas City", value: "Kansas City", state: "MO" },
  { label: "Long Beach", value: "Long Beach", state: "CA" },
  { label: "Mesa", value: "Mesa", state: "AZ" },
  { label: "Virginia Beach", value: "Virginia Beach", state: "VA" },
  { label: "Atlanta", value: "Atlanta", state: "GA" },
  { label: "Colorado Springs", value: "Colorado Springs", state: "CO" },
  { label: "Raleigh", value: "Raleigh", state: "NC" },
  { label: "Miami", value: "Miami", state: "FL" },
  { label: "Cleveland", value: "Cleveland", state: "OH" },
  { label: "Tulsa", value: "Tulsa", state: "OK" },
  { label: "Oakland", value: "Oakland", state: "CA" },
  { label: "Minneapolis", value: "Minneapolis", state: "MN" },
  { label: "Wichita", value: "Wichita", state: "KS" },
  { label: "Arlington", value: "Arlington", state: "TX" },
  { label: "Bakersfield", value: "Bakersfield", state: "CA" },
  { label: "Tampa", value: "Tampa", state: "FL" },
  { label: "Honolulu", value: "Honolulu", state: "HI" },
  { label: "Aurora", value: "Aurora", state: "CO" },
  { label: "Anaheim", value: "Anaheim", state: "CA" },
  { label: "Santa Ana", value: "Santa Ana", state: "CA" },
  { label: "Corpus Christi", value: "Corpus Christi", state: "TX" },
  { label: "Riverside", value: "Riverside", state: "CA" },
  { label: "St. Louis", value: "St. Louis", state: "MO" },
  { label: "Lexington", value: "Lexington", state: "KY" },
  { label: "Stockton", value: "Stockton", state: "CA" },
  { label: "Henderson", value: "Henderson", state: "NV" },
  { label: "Greensboro", value: "Greensboro", state: "NC" },
  { label: "Jersey City", value: "Jersey City", state: "NJ" },
  { label: "Chula Vista", value: "Chula Vista", state: "CA" },
  { label: "Buffalo", value: "Buffalo", state: "NY" },
  { label: "Fort Wayne", value: "Fort Wayne", state: "IN" },
  { label: "Knoxville", value: "Knoxville", state: "TN" },
  { label: "St. Paul", value: "St. Paul", state: "MN" },
  { label: "Winston-Salem", value: "Winston-Salem", state: "NC" },
  { label: "Garland", value: "Garland", state: "TX" },
  { label: "Glendale", value: "Glendale", state: "AZ" },
  { label: "Hialeah", value: "Hialeah", state: "FL" },
  { label: "Norfolk", value: "Norfolk", state: "VA" },
  { label: "Chandler", value: "Chandler", state: "AZ" },
  { label: "Laredo", value: "Laredo", state: "TX" },
  { label: "Madison", value: "Madison", state: "WI" },
  { label: "Reno", value: "Reno", state: "NV" },
  { label: "Baton Rouge", value: "Baton Rouge", state: "LA" },
  { label: "Irvine", value: "Irvine", state: "CA" },
  { label: "Lubbock", value: "Lubbock", state: "TX" },
  { label: "Gilbert", value: "Gilbert", state: "AZ" },
  { label: "Waco", value: "Waco", state: "TX" },
  { label: "Fremont", value: "Fremont", state: "CA" },
  { label: "Spokane", value: "Spokane", state: "WA" },
  { label: "Des Moines", value: "Des Moines", state: "IA" },
  { label: "Modesto", value: "Modesto", state: "CA" },
  { label: "Birmingham", value: "Birmingham", state: "AL" },
  { label: "Tacoma", value: "Tacoma", state: "WA" },
  { label: "Shreveport", value: "Shreveport", state: "LA" },
  { label: "Chattanooga", value: "Chattanooga", state: "TN" },
  { label: "Denton", value: "Denton", state: "TX" },
  { label: "Columbus", value: "Columbus", state: "OH" },
];
